"""Realtime client for the ComprasMX public portal.

The portal is an Angular SPA whose API (`/whitney/sitiopublico/...`) signs every
request with per-call anti-bot tokens (grc/xgrc headers) generated by its own
JavaScript. Rather than reverse-engineer the tokens (fragile, against the
spirit), we drive the real SPA with scrapling and capture the responses of the
calls the app itself makes — riding the site's own auth.

Two endpoints:
  list   GET /whitney/sitiopublico/expedientes?rows=&page=     (procedures)
  detail GET /whitney/sitiopublico/expedientes/{uuid}?id_proceso=procedimiento
         (full record incl. `drc` = awarded contracts: supplier name + amounts)

The list endpoint exposes NO supplier RFC; awards in `drc` carry `licitante`
(name) only. Realtime supplier identity is therefore name-based (lower
confidence than the RFC join in the annual batch) — callers must treat it as a
screen requiring verification, never a verdict.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from urllib.parse import quote

BASE_SPA = "https://upcp-compranet.buengobierno.gob.mx/sitiopublico/#/"
DETAIL_SPA = (
    "https://upcp-compranet.buengobierno.gob.mx/sitiopublico/#/sitiopublico/"
    "detalle/{uuid}/procedimiento"
)
CAPTURE = r"whitney/sitiopublico/expedientes"


@dataclass
class Procedure:
    uuid: str
    numero: str
    nombre: str
    siglas: str
    estatus: str
    tipo_procedimiento: str
    tipo_contratacion: str
    caracter: str
    entidad: str
    unidad_compradora: str
    fecha_apertura: str | None
    cod_expediente: str
    raw: dict = field(repr=False, default_factory=dict)

    @classmethod
    def from_row(cls, r: dict) -> "Procedure":
        return cls(
            uuid=r.get("uuid_procedimiento", ""),
            numero=r.get("numero_procedimiento", ""),
            nombre=r.get("nombre_procedimiento", ""),
            siglas=r.get("siglas", ""),
            estatus=r.get("estatus", ""),
            tipo_procedimiento=r.get("tipo_procedimiento", ""),
            tipo_contratacion=r.get("tipo_contratacion", ""),
            caracter=r.get("caracter", ""),
            entidad=r.get("entidad_federativa_contratacion", ""),
            unidad_compradora=r.get("unidad_compradora", ""),
            fecha_apertura=r.get("fecha_apertura"),
            cod_expediente=r.get("cod_expediente", ""),
            raw=r,
        )


@dataclass
class Award:
    licitante: str
    importe: float | None
    importe_max: float | None
    moneda: str
    institucion: str
    estatus: str
    titulo: str
    fecha_inicio: str | None
    fecha_publicacion: str | None
    cod_drc: str


def _first_json(page, url_contains):
    for x in getattr(page, "captured_xhr", []) or []:
        if url_contains in x.url:
            try:
                return json.loads(x.body)
            except Exception:
                continue
    return None


class ComprasMXClient:
    """Wraps a single scrapling DynamicSession; reuse across calls in one poll."""

    def __init__(self, headless: bool = True, wait_ms: int = 8000):
        from scrapling.fetchers import DynamicSession  # lazy: heavy import

        self._wait = wait_ms
        self._session_cm = DynamicSession(
            headless=headless, network_idle=True, capture_xhr=CAPTURE
        )
        self._s = None

    def __enter__(self):
        self._s = self._session_cm.__enter__()
        return self

    def __exit__(self, *a):
        return self._session_cm.__exit__(*a)

    def fetch_recent(self, rows: int = 100, page: int = 1) -> list[Procedure]:
        """Most-recent procedures (the list endpoint fires on SPA load)."""
        url = f"{BASE_SPA}"
        p = self._s.fetch(url, load_dom=True, wait=self._wait)
        data = _first_json(p, "/expedientes?")
        if not data or not data.get("success"):
            return []
        block = data["data"][0]
        return [Procedure.from_row(r) for r in block["registros"]]

    def fetch_detail(self, uuid: str) -> tuple[dict | None, list[Award]]:
        """Full record + parsed awards (drc) for one procedure."""
        url = DETAIL_SPA.format(uuid=uuid)
        p = self._s.fetch(url, load_dom=True, wait=self._wait)
        data = _first_json(p, f"/expedientes/{uuid}?")
        if not data or not data.get("success"):
            return None, []
        d = data["data"]
        obj = d[0] if isinstance(d, list) else d
        registro = (obj.get("registro") or [{}])[0]
        awards = []
        for a in obj.get("drc") or []:
            awards.append(
                Award(
                    licitante=a.get("licitante", ""),
                    importe=_num(a.get("importe")),
                    importe_max=_num(a.get("importe_max")),
                    moneda=a.get("nombre_moneda", ""),
                    institucion=a.get("nombre_institucion", ""),
                    estatus=a.get("estatus_nombre", ""),
                    titulo=a.get("titulo_contrato", ""),
                    fecha_inicio=a.get("fecha_inicio_contrato"),
                    fecha_publicacion=a.get("fecha_publicacion"),
                    cod_drc=a.get("cod_drc", ""),
                )
            )
        return registro, awards


def _num(v):
    try:
        return float(str(v).replace(",", ""))
    except (TypeError, ValueError):
        return None
