"""Realtime client for the ComprasMX public portal.

The portal is an Angular SPA whose API (`/whitney/sitiopublico/...`) signs every
request with per-call anti-bot tokens (grc/xgrc headers) generated by its own
JavaScript. Rather than reverse-engineer the tokens (fragile, against the
spirit), we drive the real SPA with scrapling and capture the responses of the
calls the app itself makes — riding the site's own auth.

Two endpoints:
  list   GET /whitney/sitiopublico/expedientes?rows=&page=     (procedures)
  detail GET /whitney/sitiopublico/expedientes/{uuid}?id_proceso=procedimiento
         (full record incl. `drc` = awarded contracts: supplier name + amounts)

The list endpoint exposes NO supplier RFC; awards in `drc` carry `licitante`
(name) only. Realtime supplier identity is therefore name-based (lower
confidence than the RFC join in the annual batch) — callers must treat it as a
screen requiring verification, never a verdict.

Known limits of the public detail JSON (verified live 2026-06-11):
  - bidder/participant lists are NOT exposed structurally — they exist only
    inside the actas PDFs under `anexos` (single-bidder detection would need
    PDF parsing);
  - `reqeconomicos` carries the LINE ITEMS (clave_cucop, quantities, min/max
    amounts) — usable for item-level price screens;
  - `lapp` is public-private-partnership project info, not bidders.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from urllib.parse import quote

BASE_SPA = "https://upcp-compranet.buengobierno.gob.mx/sitiopublico/#/"
DETAIL_SPA = (
    "https://upcp-compranet.buengobierno.gob.mx/sitiopublico/#/sitiopublico/"
    "detalle/{uuid}/procedimiento"
)
CAPTURE = r"whitney/sitiopublico/expedientes"


@dataclass
class Procedure:
    uuid: str
    numero: str
    nombre: str
    siglas: str
    estatus: str
    tipo_procedimiento: str
    tipo_contratacion: str
    caracter: str
    entidad: str
    unidad_compradora: str
    fecha_apertura: str | None
    cod_expediente: str
    raw: dict = field(repr=False, default_factory=dict)

    @classmethod
    def from_row(cls, r: dict) -> "Procedure":
        # un null JSON explícito (no clave ausente) debe dar "" en campos str,
        # no None — poll.py confía en p.estatus.upper() sin guardas.
        g = lambda k: r.get(k) or ""
        return cls(
            uuid=g("uuid_procedimiento"), numero=g("numero_procedimiento"),
            nombre=g("nombre_procedimiento"), siglas=g("siglas"),
            estatus=g("estatus"), tipo_procedimiento=g("tipo_procedimiento"),
            tipo_contratacion=g("tipo_contratacion"), caracter=g("caracter"),
            entidad=g("entidad_federativa_contratacion"),
            unidad_compradora=g("unidad_compradora"),
            fecha_apertura=r.get("fecha_apertura"),
            cod_expediente=g("cod_expediente"), raw=r,
        )


@dataclass
class Award:
    licitante: str
    importe: float | None
    importe_max: float | None
    moneda: str
    institucion: str
    estatus: str
    titulo: str
    fecha_inicio: str | None
    fecha_publicacion: str | None
    cod_drc: str


def _first_json(page, url_contains):
    for x in getattr(page, "captured_xhr", []) or []:
        if url_contains in x.url:
            try:
                return json.loads(x.body)
            except Exception:
                continue
    return None


def _all_json(page, url_contains):
    out = []
    for x in getattr(page, "captured_xhr", []) or []:
        if url_contains in x.url:
            try:
                out.append(json.loads(x.body))
            except Exception:
                continue
    return out


def merge_list_pages(payloads: list[dict]) -> list[dict]:
    """Une las respuestas capturadas del listado (una por página), dedup por
    uuid: el portal puede repetir filas entre clics si publica en medio."""
    rows, seen = [], set()
    for data in payloads:
        if not isinstance(data, dict) or not data.get("success"):
            continue
        for block in data.get("data") or []:
            for r in block.get("registros") or []:
                u = r.get("uuid_procedimiento")
                if u and u in seen:
                    continue
                if u:
                    seen.add(u)
                rows.append(r)
    return rows


class ComprasMXClient:
    """Wraps a single scrapling DynamicSession; reuse across calls in one poll."""

    def __init__(self, headless: bool = True, wait_ms: int = 8000):
        from scrapling.fetchers import DynamicSession  # lazy: heavy import

        self._wait = wait_ms
        self._session_cm = DynamicSession(
            headless=headless, network_idle=True, capture_xhr=CAPTURE
        )
        self._s = None

    def __enter__(self):
        self._s = self._session_cm.__enter__()
        return self

    def __exit__(self, *a):
        return self._session_cm.__exit__(*a)

    def fetch_recent(self, pages: int = 1) -> list[Procedure]:
        """Most-recent procedures. The SPA loads 100 rows per page
        (`expedientes?rows=100&page=N`); clicking the PrimeNG paginator fires
        one capturable XHR per page. `pages` > 1 widens the window so a poll
        every 30 min can't miss a burst of publications on the first page."""
        url = f"{BASE_SPA}"

        def _paginate(page):
            for _ in range(pages - 1):
                page.wait_for_timeout(1500)
                try:
                    page.click("button.p-paginator-next:not(.p-disabled)",
                               timeout=4000)
                except Exception:
                    break  # última página alcanzada o paginador cambió
            page.wait_for_timeout(2500)
            return page

        if pages > 1:
            p = self._s.fetch(url, load_dom=True, wait=self._wait,
                              page_action=_paginate)
        else:
            p = self._s.fetch(url, load_dom=True, wait=self._wait)
        payloads = _all_json(p, "/expedientes?")
        if not payloads:
            print("WARN: no se capturó la respuesta del listado — portal "
                  "caído o cambio en la SPA (no es un feed vacío)")
            return []
        if not any(d.get("success") for d in payloads if isinstance(d, dict)):
            print(f"WARN: el portal respondió success=false: {str(payloads[0])[:120]}")
            return []
        return [Procedure.from_row(r) for r in merge_list_pages(payloads)]

    def fetch_detail(self, uuid: str) -> tuple[dict | None, list[Award]]:
        """Full record + parsed awards (drc) for one procedure."""
        url = DETAIL_SPA.format(uuid=uuid)
        p = self._s.fetch(url, load_dom=True, wait=self._wait)
        data = _first_json(p, f"/expedientes/{uuid}?")
        if not data or not data.get("success"):
            return None, []
        d = data["data"]
        obj = d[0] if isinstance(d, list) else d
        registro = (obj.get("registro") or [{}])[0]
        awards = []
        for a in obj.get("drc") or []:
            awards.append(
                Award(
                    licitante=a.get("licitante", ""),
                    importe=_num(a.get("importe")),
                    importe_max=_num(a.get("importe_max")),
                    moneda=a.get("nombre_moneda", ""),
                    institucion=a.get("nombre_institucion", ""),
                    estatus=a.get("estatus_nombre", ""),
                    titulo=a.get("titulo_contrato", ""),
                    fecha_inicio=a.get("fecha_inicio_contrato"),
                    fecha_publicacion=a.get("fecha_publicacion"),
                    cod_drc=a.get("cod_drc", ""),
                )
            )
        return registro, awards


def _num(v):
    try:
        return float(str(v).replace(",", ""))
    except (TypeError, ValueError):
        return None
